apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-blue
  template:
    metadata:
      labels:
        app: web-blue
    spec:
      containers:
        - name: web-blue
          image: fabricioveronez/web-color:blue
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
      tolerations:
        - key: gpu
          operator: Equal
          value: "true"
          effect: NoSchedule
