apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-configuracao
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-configuracao
  template:
    metadata:
      labels:
        app: app-configuracao
    spec:
      containers:
        - name: app-configuracao
          image: kubedevio/app-variaveis-ambiente:v1
          ports:
            - containerPort: 3000
          env:
            - name: APP_NAME
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: APP_NAME_CONFIG
            - name: APP_VERSION
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: APP_VERSION_CONFIG
            - name: APP_AUTHOR
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: APP_AUTHOR_CONFIG
---
apiVersion: v1
kind: Service
metadata:
  name: app-configuracao
spec:
  selector:
    app: app-configuracao
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 3000
      nodePort: 30000
  type: NodePort
