apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: fabricioveronez/simulador-do-caos
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 500m
              memory: 1.5Gi
            limits:
              cpu: 500m
              memory: 1.5Gi
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 500m
              memory: 1.5Gi
            limits:
              cpu: 500m
              memory: 1.5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  selector:
    app: web
  ports:
    - name: web
      port: 80
      targetPort: 3000
      nodePort: 30000
    - name: nginx
      port: 8080
      targetPort: 80
  type: LoadBalancer
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: web
spec:
  minReplicas: 1
  maxReplicas: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web
  metrics:
    - type: ContainerResource
      containerResource:
        container: web
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    - type: ContainerResource
      containerResource:
        container: nginx
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
        - periodSeconds: 15
          type: Percent
          value: 100
        - periodSeconds: 15
          type: Pods
          value: 2
      selectPolicy: Max
    scaleDown:
      stabilizationWindowSeconds: 10
      policies:
        - periodSeconds: 15
          type: Percent
          value: 100
        - periodSeconds: 15
          type: Pods
          value: 2
      selectPolicy: Min
