apiVersion: v1
kind: ServiceAccount
metadata:
  name: conversaotemperatura
---
apiVersion: v1
kind: Secret
metadata:
  name: web-secret
  annotations:
    kubernetes.io/service-account.name: conversaotemperatura
type: kubernetes.io/service-account-token
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversaotemperatura
spec:
  replicas: 1
  selector:
    matchLabels:
      app: conversaotemperatura
  template:
    metadata:
      labels:
        app: conversaotemperatura
    spec:
      serviceAccount: conversaotemperatura
      containers:
        - name: conversao
          image: limalucas99/conversao-temperatura:v1
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: conversaotemperatura
spec:
  selector:
    app: conversaotemperatura
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
      nodePort: 30000
