apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-color
spec:
  selector:
    matchLabels:
      app: web-color
  template:
    metadata:
      labels:
        app: web-color
    spec:
      initContainers:
        - name: start
          image: fabricioveronez/ubuntu-curl:v1
          command: ["sh", "-c", "curl http://web-color -o /app/index.html"]
          volumeMounts:
            - mountPath: /app
              name: nginx-vol
      containers:
        - name: web-color
          image: fabricioveronez/web-color:blue
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: nginx-vol
      volumes:
        - name: nginx-vol
          emptyDir:
            sizeLimit: 30Mi
---
apiVersion: v1
kind: Service
metadata:
  name: web-color
spec:
  selector:
    app: web-color
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
